name: SE-adLIF

channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults

dependencies:
  - pip
  - python=3.11.8
  - pytorch==2.5.1
  - pytorch-cuda==12.1
  - torchaudio==2.5.1
  - pytorch-lightning==2.2.1
  - hydra-core==1.3.2
  - matplotlib
  
  - pip:
    - jax==0.5.0
    - jax-cuda12-pjrt==0.5.0
    - jax-cuda12-plugin==0.5.0
    - jaxlib==0.5.0
    - auraloss==0.4.0
    - librosa==0.10.2
    - tonic
