# TODO: update
name: cLSNN

channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - pip
  - python=3.11.6
  - matplotlib==3.8.3
  - pytorch==2.1.2
  - pytorch-cuda==12.1
  - torchaudio==2.1.2
  - pytorch-lightning==2.2.1

  - pip:
      - aim==3.19.1
      - hydra_core==1.3.2
