defaults:
  - _self_
  - override hydra/job_logging: none # to disable hydra logging
path_to_model_output: /home/romirates/results/se_adlif/45/3
wave_files_path: /home/romirates/results/16000_peak
logdir: ./results
exp_name: comp_metric_run

hydra:
  job:
    chdir: true
  run:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}