defaults:
  - _self_
  - override hydra/job_logging: none # to disable hydra logging
model: se_adlif # se_adlif, ef_adlif, lif model 
ckpt_path: "/home/romirates/SE-adlif/results/hydra/2025-01-27/21-48-56/2/ckpt/epoch=9-step=93800.ckpt"
save_to: "/home/romirates/results/ef_adlif/2/9"
test_dir_path: "/home/romirates/results/16000_peak"
logdir: ./results
exp_name: eval_run

hydra:
  job:
    chdir: true
  run:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}