defaults:
  - _self_
  - override hydra/job_logging: none # to disable hydra logging
ckpt_path: /path/to/ckpt/example.ckpt
source_wave_path: "/path/to/libritts/location/"
pred_wave_path: "/path/to/prediction/"
encoder_only: False

logdir: ./results
exp_name: generate_waves

hydra:
  job:
    chdir: true
  run:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}