defaults:
  - _self_
  - dataset: shd
  - experiment: SHD_SE_adLIF_small

random_seed: 42

logdir: ./results

datadir: ./data

hydra:  
  job:
    chdir: true
  run:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${logdir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}