defaults:
  - _self_
  - data: ???
  - experiment: SHD_SE_adLIF_small

random_seed: 42

logdir: ./results

hydra:  
  job:
    chdir: true
  run:
    dir: ${result_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}