# class_path: datasets.pl_dataset.SHDLDM
# init_args:
_target_: datasets.audio_compress.CompressLibri
name: Compress libri task
required_model_size: small
data_path: ${datadir}
cache_path: ${cachedir}
max_sample: -1
sampling_freq: 16000
sample_length: 1024
# allow to do y[t - delay] L(x[0:t]) instead to of y[t] = L(x[0:t]) 
# where L is the SNN model, it prevents that the neuron should respond directly
# to be fair with a spectral loss it may not really matter if the neuron respond with a temporal shift
prediction_delay: 20
zero_input_proba: 0.0
batch_size: 128
num_workers: 8
fits_into_ram: True
num_classes: 1
normalization: 'peak'
debug: True

